global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8002']

  - job_name: 'profile-service'
    static_configs:
      - targets: ['profile-service:8006']

  - job_name: 'audit-service'
    static_configs:
      - targets: ['audit-service:8001']

  - job_name: 'access-service'
    static_configs:
      - targets: ['access-service:8000']

  - job_name: 'config-service'
    static_configs:
      - targets: ['config-service:8003']

  - job_name: 'file-service'
    static_configs:
      - targets: ['file-service:8004']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8005']

  - job_name: 'subscription-service'
    static_configs:
      - targets: ['subscription-service:8007']


