version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cloudstorage
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - cloudstorage-net

  auth-service:
    build: ./auth
    ports:
      - "8002:8002"
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/cloudstorage
      - JWT_SECRET=your_strong_secret_123
    depends_on:
      - db
    networks:
      - cloudstorage-net

  profile-service:
    build: ./profile
    ports:
      - "8006:8006"
    environment:
      - PORT=3002
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/cloudstorage
      - JWT_SECRET=your_strong_secret_123
    depends_on:
      - db
    networks:
      - cloudstorage-net

  audit-service:
    build: ./audit
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/cloudstorage
    depends_on:
      - db
    networks:
      - cloudstorage-net

  access-service:
    build: ./access
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/cloudstorage
    depends_on:
      - db
    networks:
      - cloudstorage-net

  config-service:
    build: ./config
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/cloudstorage
    depends_on:
      - db
    networks:
      - cloudstorage-net

  file-service:
    build: ./file
    ports:
      - "8004:8004"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/cloudstorage
    depends_on:
      - db
    networks:
      - cloudstorage-net

  notification-service:
    build: ./notification
    ports:
      - "8005:8005"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/cloudstorage
    depends_on:
      - db
    networks:
      - cloudstorage-net

  subscription-service:
    build: ./subscription
    ports:
      - "8007:8007"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/cloudstorage
    depends_on:
      - db
    networks:
      - cloudstorage-net

volumes:
  pgdata:

networks:
  cloudstorage-net:
    driver: bridge